name: Run Test on Label

on:
  pull_request:
    types:
      - labeled

jobs:
  run-test:
    if: github.event.label.name == 'run test'  # Runs only if 'run test' label is added
    runs-on: ubuntu-latest

    steps:
      - name: Print Running Message (Red)
        run: echo -e "\033[31mRunning flow...\033[0m"  # Prints in red

      - name: Print Completed Message (Green)
        run: echo -e "\033[32mCompleted\033[0m"  # Prints in green

      - name: Add PR Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "✅ Finished."
            })
