name: Quick Issue
description: "This Quick Issue template is for fast lazy report."
title: "[type(Scope)]: Brief description of the issue"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        > Please provide the necessary details for this issue by completing the sections below.
  - type: checkboxes
    id: duplicate-check
    attributes:
      label: "Duplicate Check"
      description: "Before creating a new issue, ensure you have searched both open and closed issues for similar problems. Do not create duplicate issues."
      options:
        - label: "I have searched the existing issues and confirmed this issue is unique."
          required: true
  - type: textarea
    id: bullet-details
    attributes:
      label: "Key Points"
      description: "List the key points or steps related to the issue in bullet format."
      placeholder: |
        - First key point
        - Second key point
        - Additional details
  - type: dropdown
    id: work-on-issue
    attributes:
      label: "Will you be working on this issue?"
      description: "Select whether you intend to work on resolving this issue."
      options:
        - "Yes, I will work on this issue."
        - "No, I will not work on this issue."
        - "I'm unsure at this moment."
