name: Quick Issue
description: "A minimal template for fast and straightforward reports."
title: "[Quick Report]:"
labels: []
body:
  - type: markdown
    attributes:
      value: "Please fill out the sections below with the essential details for your report."
  - type: checkboxes
    id: duplicate-check
    attributes:
      label: "Duplicate Check"
      description: "Before submitting, verify that you haven't already reported this issue by checking both open and closed issues."
      options:
        - label: "I have reviewed existing issues and confirmed this report is unique."
          required: true
  - type: textarea
    id: bullet-details
    attributes:
      label: "Key Points"
      description: "Summarize the main points or steps related to the issue using bullet points."
      placeholder: |
        - First key point
        - Second key point
        - Additional details
  - type: dropdown
    id: work-on-issue
    attributes:
      label: "Are you planning to work on this issue?"
      description: "Let us know if you intend to address this issue yourself."
      options:
        - "Yes, I will work on this issue."
        - "No, I am not able to work on this issue."
        - "Not sure yet."
