name: Quick Issue
description: "Quickly create a new issue using our standardized template."
title: "[Scope(optional)]: Short Title"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## Issue Details
        Please provide detailed information for this issue by filling out the sections below.
  - type: input
    id: title-input
    attributes:
      label: "Issue Title (with optional scope)"
      description: "Provide a concise title for the issue. Using a conventional commit style (e.g., `feat(ui): add dropdown for settings`) helps maintain consistency."
      placeholder: "feat(scope): Brief description of the issue"
  - type: checkboxes
    id: duplicate-check
    attributes:
      label: "Duplicate Check"
      description: "Confirm that you have reviewed both open and closed issues for duplicates before submitting. Check the box if this issue is unique."
      options:
        - label: "I have verified and this issue is unique."
          value: unique
  - type: textarea
    id: bullet-details
    attributes:
      label: "Key Details"
      description: "Outline the main points, steps, or context for this issue in bullet format."
      placeholder: "- Point one\n- Point two\n- Additional details"
  - type: dropdown
    id: work-on-issue
    attributes:
      label: "Do you intend to work on this issue?"
      description: "Select your preferred option."
      options:
        - label: "Yes, I will work on this issue."
          value: yes
        - label: "No, I will not be working on this issue."
          value: no
        - label: "I'm unsure at the moment."
          value: unsure
