name: Auto Annotate commits

permissions:
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      PullRequestLink:
        description: "Enter the Pull Request Link"
        required: true
        type: string

jobs:
  fetch-pr-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check And Validate PR Inuput Link
        run: | 
          INPUT_URL="${{ github.event.inputs.PullRequestLink }}"
          BASE_REPO="${{ github.repository }}/" 
          GITHUB_BASE_URL="https://github.com/"
          RESOURCE_TYPE="pull/"

          echo "::notice:: Validating URL: $INPUT_URL"

          if [[ ! "$INPUT_URL" == "$GITHUB_BASE_URL"* ]]; then
              echo "::error:: Base URL didn't match. Expected: $GITHUB_BASE_URL"
              exit 1
          fi

          if [[ ! "$INPUT_URL" == "$GITHUB_BASE_URL$BASE_REPO"* ]]; then
              echo "::error:: PR does not belong to this repository. Expected prefix: $GITHUB_BASE_URL$BASE_REPO"
              exit 1
          fi

          if [[ ! "$INPUT_URL" == "$GITHUB_BASE_URL$BASE_REPO$RESOURCE_TYPE"* ]]; then
              echo "::error:: Not a pull request link. Expected: ${GITHUB_BASE_URL}${BASE_REPO}${RESOURCE_TYPE}..."
              exit 1
          fi


          PR_SCHEMA="$GITHUB_BASE_URL$BASE_REPO$RESOURCE_TYPE"

          RESOURCE_ID_PART="${INPUT_URL#$PR_SCHEMA}"

          if [[ "$RESOURCE_ID_PART" =~ ^([0-9]+) ]]; then
              PR_NUMBER="${BASH_REMATCH[1]}"
          else
              echo "::error:: Can't find PR ID or PR ID is not a number. Check URL. Expected: ${GITHUB_BASE_URL}${BASE_REPO}${RESOURCE_TYPE}<NUMBER>"
              exit 1
          fi


          echo "URL validation successful! $PR_SCHEMA$RESOURCE_ID"
