name: Comment Triggered Workflow

on:
  issue_comment:
    types: [created, edited]


permissions:
  pull-requests: write
  issues: write
jobs:
  comment_action:
    runs-on: ubuntu-latest
    steps:
      - name: Check Comment Body
        if: contains(github.event.comment.body, '/run-tests')
        run: |
          echo "Comment triggered with /run-tests command."

      - name: Comment check for rework
        if: contains(github.event.comment.body, '/needs-rework')
        run: |
          echo "Comment triggered with /needs-rework command. exiting"
          exit 1
      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (context.payload.issue.pull_request) {
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                body: "Workflow triggered by comment."
              })
            }
