name: Build All Workflow

on:
  workflow_dispatch:

jobs:
  build-all-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          cache: false
          check-latest: true

      - name: Cache Go modules - testing-env/server
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/testing-env/server/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Display Build Help message
        run: make help

      - name: Build All Components
        run: make build-all

      - name: Ensure bin directory exists
        run: mkdir -p bin

      - name: Upload Built Binaries
        uses: actions/upload-artifact@v4
        with:
          name: built-binaries
          path: bin/*
          if-no-files-found: error
          retention-days: 4
