name: Build and Test

on:
  repository_dispatch:
    types: [run-build-test]

permissions:
  checks: write
  contents: read

jobs:
  run-build-test:
    if: contains(github.event.comment.body, '/run-build-test')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug Input Values
      # run: |
      #   echo -e "\033[34mPull Request Number:\033[0m \033[1;33m${{ github.event.inputs.pr_number }}\033[0m"
      #   echo -e "\033[34mPull Request SHA:\033[0m \033[1;32m${{ github.event.inputs.pr_sha }}\033[0m"
      run: |
        echo -e "\033[34mPull Request Number:\033[0m \033[1;33m${{ github.event.client_payload.pr_number }}\033[0m"
        echo -e "\033[34mPull Request SHA:\033[0m \033[1;32m${{ github.event.client_payload.pr_sha }}\033[0m"

    - name: Show files
      run: ls 

    - name: Print Running Message (Red)
      run: echo -e "\033[31mRunning test flow...\033[0m"

    - name: Print Completed Message (Green)
      run: echo -e "\033[32mTest flow completed successfully!\033[0m"
