name: PR Check

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-test
          path: artifact

      - name: Extract PR Info
        run: |
          SHA=$(jq -r '.headRefOid' artifact/artifact.json)
          PR_NUMBER=$(jq -r '.number' artifact/artifact.json)
          echo "SHA=$SHA" >> $GITHUB_ENV
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "PR_URL=https://github.com/${{ github.repository }}/pull/$PR_NUMBER" >> $GITHUB_ENV

      - name: Run Simple Check
        run: |
          echo -e "\033[0;32m✅ This test is running\033[0m"

      - name: Update PR Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const sha = process.env.SHA;
            const prUrl = process.env.PR_URL;

            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: "success",
              context: "PR Check",
              description: "✅ Check passed! You can merge.",
              target_url: prUrl
            });
