name: PR Check

on:
  workflow_dispatch:

permissions:
  actions: write
  pull-requests: write

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: context-metadata
          path: artifact

      - name: Unzip Artifact
        run: unzip artifact/context-metadata.zip -d artifact/

      - name: Extract PR Info
        run: |
          SHA=$(cat artifact/PullRequestData.txt | jq -r .headRefOid) >> $GITHUB_ENV
          PR_NUMBER=$(cat artifact/PullRequestData.txt | jq -r .number) >> $GITHUB_ENV
          PR_URL=$(cat artifact/PullRequestData.txt | jq -r .url) >> $GITHUB_ENV

      - name: Run Simple Check
        run: |
          echo -e "\033[0;32m✅ This test is running\033[0m"

      - name: Update PR Status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const sha = process.env.SHA;
            const prUrl = process.env.PR_URL;

            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: "success",
              context: "PR Check",
              description: "✅ Check passed! You can merge.",
              target_url: prUrl
            });
