name: Comment Listener

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  check-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check comment
      id: check_comment
      run: |
        COMMENT_BODY="${{ github.event.comment.body }}"
        if [[ "$COMMENT_BODY" == "/run-build-test" ]]; then
          echo "RESULT=run-build-test" >> $GITHUB_ENV
        else
          echo "RESULT=no-action" >> $GITHUB_ENV
        fi

    - name: Trigger workflow
      if: env.RESULT == 'run-build-test'
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-and-test.yml/dispatches \
          -d '{
            "ref": "${{ github.event.issue.pull_request.head.ref }}",
            "inputs": {
              "pr_number": "${{ github.event.issue.number }}",
              "pr_sha": "${{ github.event.issue.pull_request.head.sha }}"
            }
          }'
