name: Comment Listener

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: read
  actions: write 

jobs:
  check-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Check comment
      id: check_comment
      run: |
        COMMENT_BODY="${{ github.event.comment.body }}"
        if [[ "$COMMENT_BODY" == *"/run-test-build"* ]]; then
          echo "RESULT=run-build-test" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "PR_SHA=${{ github.event.issue.pull_request.head.sha }}" >> $GITHUB_ENV
        else
          echo "RESULT=no-action" >> $GITHUB_ENV
        fi

    - name: Trigger workflow
      if: env.RESULT == 'run-build-test'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: run-build-test
        client-payload: '{"pr_number": "${{ env.PR_NUMBER }}", "pr_sha": "${{ env.PR_SHA }}"}'
