name: Comment Listener

on:
  issue_comment:
    types: [created]

jobs:
  check-comment:
    runs-on: ubuntu-latest

    steps:

    - name: Print pull Request sha (Red)
      run: echo -e "\033[31m PR SHA => ${{ github.event.issue.pull_request.head.sha }}...\033[0m"

    - name: Print Pull Request number (Green)
      run: echo -e "\033[32m PR number is => ${{ github.event.issue.number }} \033[0m"

    - name: Check comment
      id: check_comment
      run: |
        COMMENT_BODY="${{ github.event.comment.body }}"
        if [[ "$COMMENT_BODY" == *"/run-test-build"* ]]; then
          echo -e "manual trigger commad detected \033[32m `/run-test-build` \033[0m continuing workflow... "
        else
          echo -e "No trigger detected \033[31m `/run-test-build` \033[0m exiting.."
          exit 1
        fi
