name: Dependency resolution 

on:
  workflow_call:

jobs:
  dependency_resolve:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Fetch Dependency
        run: make deps-all
