name: Go Cache

on:
  workflow_call:

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'


      - name: Cache Reverse Proxy
        id: cache-reverse-proxy
        run: |
          if [ -f firewall/reverseProxy/go.sum ]; then
            echo "CACHE_KEY=${{ runner.os }}-go-reverseProxy-$(sha256sum firewall/reverseProxy/go.sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          else
            echo "CACHE_KEY=" >> $GITHUB_OUTPUT
          fi
      - uses: actions/cache@v4
        if: ${{ steps.cache-reverse-proxy.outputs.CACHE_KEY != '' }}
        with:
          path: ~/go/pkg/mod
          key: ${{ steps.cache-reverse-proxy.outputs.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-go-reverseProxy-


      - name: Cache WAF
        id: cache-waf
        run: |
          if [ -f firewall/waf/go.sum ]; then
            echo "CACHE_KEY=${{ runner.os }}-go-waf-$(sha256sum firewall/waf/go.sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          else
            echo "CACHE_KEY=" >> $GITHUB_OUTPUT
          fi
      - uses: actions/cache@v4
        if: ${{ steps.cache-waf.outputs.CACHE_KEY != '' }}
        with:
          path: ~/go/pkg/mod
          key: ${{ steps.cache-waf.outputs.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-go-waf-


      - name: Cache Application
        id: cache-application
        run: |
          if [ -f testing-env/application/go.sum ]; then
            echo "CACHE_KEY=${{ runner.os }}-go-application-$(sha256sum testing-env/application/go.sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          else
            echo "CACHE_KEY=" >> $GITHUB_OUTPUT
          fi
      - uses: actions/cache@v4
        if: ${{ steps.cache-application.outputs.CACHE_KEY != '' }}
        with:
          path: ~/go/pkg/mod
          key: ${{ steps.cache-application.outputs.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-go-application-


      - name: Cache Server
        id: cache-server
        run: |
          if [ -f testing-env/server/go.sum ]; then
            echo "CACHE_KEY=${{ runner.os }}-go-server-$(sha256sum testing-env/server/go.sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          else
            echo "CACHE_KEY=" >> $GITHUB_OUTPUT
          fi
      - uses: actions/cache@v4
        if: ${{ steps.cache-server.outputs.CACHE_KEY != '' }}
        with:
          path: ~/go/pkg/mod
          key: ${{ steps.cache-server.outputs.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-go-server-


      - name: Cache Simulator
        id: cache-simulator
        run: |
          if [ -f testing-env/simulator/go.sum ]; then
            echo "CACHE_KEY=${{ runner.os }}-go-simulator-$(sha256sum testing-env/simulator/go.sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          else
            echo "CACHE_KEY=" >> $GITHUB_OUTPUT
          fi
      - uses: actions/cache@v4
        if: ${{ steps.cache-simulator.outputs.CACHE_KEY != '' }}
        with:
          path: ~/go/pkg/mod
          key: ${{ steps.cache-simulator.outputs.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-go-simulator-
