name: Build Reverse Proxy 

on:
  workflow_call:

jobs:
  dependency_resolve:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Compile Reverse Proxy Component
        run: make build-reverseProxy
