name: Context Preserve

permissions:
  actions: write

on:
  workflow_dispatch:
    inputs:
      PullRequestLink:
        description: "Enter the Pull Request Link"
        required: true

jobs:
  Context-Preserver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch PR data
        id: GetPullRequestData
        run: |
          PR_JSON=$(gh pr view "${{ github.event.inputs.PullRequestLink }}" --json number,headRefOid)
          if [ $? -ne 0 ]; then
            echo "Error: Failed to fetch PR data."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete existing artifact (if any)
        uses: geekyeggo/delete-artifact@v2
        with:
          name: context-metadata
        continue-on-error: true

      - name: Save PR Number and SHA as artifacts
        run: |
          echo "$PR_JSON" > PullRequestData.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: context-metadata
          path: |
            PullRequestData.txt
