name: Context Preserve

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  workflow_dispatch:
    inputs:
      PullRequestLink:
        description: "Enter the Pull Request Link"
        required: true

jobs:
  Context-Preserver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch PR data
        id: GetPullRequestData
        run: |
          gh pr view "${{ github.event.inputs.PullRequestLink }}" --json number,headRefOid,url > PullRequestData.txt
          if [ $? -ne 0 ]; then
            echo "Error: Failed to fetch PR data."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: context-metadata
          path: |
            PullRequestData.txt

      # - name: Create and Run Check
      #   uses: actions/github-script@v7
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const fs = require('fs').promises;
      #
      #       const prData = JSON.parse(await fs.readFile('PullRequestData.txt', 'utf8'));
      #       const sha = prData.headRefOid;
      #       const prNumber = prData.number;
      #       const prUrl = prData.url;
      #
      #       const check = await github.rest.checks.create({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         name: 'Check build Test',
      #         head_sha: sha,
      #         status: 'in_progress',
      #         output: {
      #           title: 'Manual PR Validation',
      #           summary: `Validating PR ${prUrl}...`
      #         }
      #       });
